import { useEffect, useState } from "react";
import StudentSidebar from "../../components/StudentSidebar";
import { fetchMyResult } from "../../services/resultApi";
import "./StudentDashboard.css";

const StudentResults = () => {
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const load = async () => {
      try {
        const res = await fetchMyResult();

        if (res.locked) {
          setResult(null);
        } else {
          setResult(res);
        }
      } catch {
        setResult(null);
      } finally {
        setLoading(false);
      }
    };

    load();
  }, []);

  if (loading) return <p>Loading results...</p>;

  if (!result) {
    return (
      <div className="student-layout">
        <StudentSidebar />
        <main className="student-main">
          <h2>Result not available yet</h2>
        </main>
      </div>
    );
  }

  // ... logic remains same ...

  return (
    <div className="student-layout">
      <StudentSidebar />

      <main className="student-main">
        <h1>Assessment Report</h1>

        <div className="result-card">
          <h3>Overall Proficiency: {result.overallPercentage}%</h3>

          <div className="category-performance-grid">
            {(result.categoryScores || []).map((c) => (
              <div key={c.category} className="category-item">
                <span className="category-name">{c.category}</span>
                <span className="category-value">{c.percentage}%</span>
              </div>
            ))}
          </div>

          <div className="insights-section">
            <div className="insight-group strengths-group">
              <h4>✨ Key Strengths</h4>
              <ul>
                {(result.strengths || []).map((s) => (
                  <li key={s}>{s}</li>
                ))}
              </ul>
            </div>

            <div className="insight-group careers-group">
              <h4>🚀 Career Pathways</h4>
              <ul>
                {(result.recommendedCareers || []).map((c) => (
                  <li key={c}>{c}</li>
                ))}
              </ul>
            </div>
          </div>

          <div className="result-footer">
            <span>Time Taken: {result.timeSpent || 0}s</span>
            <span>Generated by AI Autopilot Engine</span>
          </div>
        </div>
      </main>
    </div>
  );
};

export default StudentResults;
